version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DEV=true
    container_name: app
    image: josemasri/django-recipie-app
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: >
      sh -c "wait-for-it.sh db:5432 && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
    env_file:
      - .env

  db:
    image: postgres:14-alpine
    container_name: db
    environment:
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env.ci-cd
