name: Checks

on:
  push:
    branches: [main]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Write env file
        run: cp .env.ci-cd .env
      - name: Test
        run: docker-compose run --rm app sh -c "wait-for-it.sh db:5432 && python manage.py test"
      - name: Lint
        run: docker-compose run --rm app sh -c "flake8"
